function AIA_v4_main
    
    % Create main figure - MAKE IT WIDER to fit new buttons
    mainFig = figure('Name', 'A.I.A - Avicii Integrated Analysis', ...
        'Position', [100, 100, 1020, 700], ...  % Made wider: 900 -> 1200
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Resize', 'on');

    % Create main panel - ADJUST WIDTH
    mainPanel = uipanel(mainFig, 'Position', [0.02, 0.05, 0.94, 0.9], ...  % Wider panel
        'Title', '', 'BorderType', 'none');
    
    % Title
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'A.I.A - Avicii Integrated Analysis', ...
        'Position', [240, 590, 500, 40], ...
        'FontSize', 20, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'));
    
    % Subtitle
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'Biology Tools', ...
        'Position', [240, 570, 500, 25], ...
        'FontSize', 14, ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'));
    
    % Section 1: Bacterial Growth Analysis
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'PlaterReader', ...
        'Position', [10, 520, 300, 25], ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'left');
    
    % Bacterial growth buttons
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 1: Data Preparation', ...
        'Position', [10, 470, 260, 40], ...
        'FontSize', 12, ...
        'Callback', @step1Callback);
    
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 2: Raw OD/LUC Analysis', ...
        'Position', [10, 420, 260, 40], ...
        'FontSize', 12, ...
        'Callback', @step2Callback);
    
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 3: Luciferase Analysis', ...
        'Position', [10, 370, 260, 40], ...
        'FontSize', 12, ...
        'Callback', @step3Callback);

    uicontrol(mainPanel, 'Style', 'pushbutton', ...
    'String', 'Step 4: Lum vs. OD ', ...
    'Position', [10, 320, 260, 40], ...
    'FontSize', 12, ...
    'Callback', @step4Callback);

    uicontrol(mainPanel, 'Style', 'pushbutton', ...
    'String', 'Step 5: 3D Lum vs. OD vs. Time', ...
    'Position', [10, 270, 260, 40], ...
    'FontSize', 12, ...
    'Callback', @step5Callback);
    
    % Section 2:
    
    % Then adjust the Universal Plate Reader button position to:
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Universal Plate Reader (GROOT)', ...
        'Position', [300, 270, 200, 40], ...  % Changed from 270 to 220
        'FontSize', 12, ...
        'Callback', @universalPlateReaderCallback); 
    
    % Image Analysis
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'All Scripts', ...
        'Position', [300, 520, 300, 25], ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'left');
    
    % Image analysis buttons
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Pellicle IP Analysis', ...
        'Position', [300, 470, 200, 40], ...
        'FontSize', 12, ...
        'Callback', @pellicleIPCallback);
    
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'BacterialG IP Analysis', ...
        'Position', [300, 420, 200, 40], ...
        'FontSize', 12, ...
        'Callback', @bacterialGIPCallback);
    
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
    'String', 'Pore Analysis', ...
    'Position', [300, 370, 200, 40], ...  % Adjust position as needed
    'FontSize', 12, ...
    'Callback', @poreAnalysisCallback);

    uicontrol(mainPanel, 'Style', 'pushbutton', ...
    'String', 'Sanger', ...
    'Position', [300, 320, 200, 40], ...
    'FontSize', 12, ...
    'Callback', @SangerCallback);

    % Add these new buttons AFTER your existing "All Scripts" section
    % Section 3: Advanced Analysis
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'Advanced Analysis', ...
        'Position', [530, 520, 300, 25], ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'left');

    % Dose-Response Analysis
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Dose-Response', ...
        'Position', [530, 470, 200, 40], ...
        'FontSize', 10, ...
        'Callback', @doseResponseCallback);

    % Colony Counter
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Colony Counter', ...
        'Position', [530, 420, 200, 40], ...
        'FontSize', 10, ...
        'Callback', @colonyCounterCallback);

    % Biofilm Analysis
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Biofilm Analysis', ...
        'Position', [530, 370, 200, 40], ...
        'FontSize', 10, ...
        'Callback', @biofilmAnalysisCallback);

    % Microscopy Tools
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Microscopy Tools', ...
        'Position', [530, 320, 200, 40], ...
        'FontSize', 10, ...
        'Callback', @microscopyCallback);

    % Section 4: Genomics & Automation
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'Genomics & Automation', ...
        'Position', [750, 520, 200, 25], ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'left');

    % Genomics Tools
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Genomics Tools', ...
        'Position', [750, 470, 200, 40], ...
        'FontSize', 10, ...
        'Callback', @genomicsCallback);

    % Batch Processing
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Batch Processing', ...
        'Position', [750, 420, 200, 40], ...
        'FontSize', 10, ...
        'Callback', @batchProcessingCallback);
    
     % Section : Calculators
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'Calculators', ...
        'Position', [750, 370, 120, 25], ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'left');
    
    % Calculator buttons
     uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Molarity', ...
        'Position', [750, 320, 100, 40], ...
        'FontSize', 12, ...
        'Callback', @MolarityCallback);

    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Media', ...
        'Position', [850, 320, 100, 40], ...
        'FontSize', 12, ...
        'Callback', @B4Callback);

    % Status text area
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'Status & Instructions:', ...
        'Position', [50, 160, 200, 20], ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'left');
    
    % Status text area - ADJUST position for wider window
    statusText = uicontrol(mainPanel, 'Style', 'text', ...
        'String', ['Welcome to Avicii Analysis World!' newline newline ...
                  'Select an analysis tool from above:' newline ...
                  '• Bacterial Growth: Process Excel data and create growth curves' newline ...
                  '• Image Processing: Analyze pellicle, bacterial growth, or pore images' newline ...
                  '• Advanced Analysis: Dose-response, colony counting, biofilm analysis' newline ...
                  '• Microscopy Tools: Cell counting, viability, fluorescence analysis' newline ...
                  '• Genomics: Primer design, restriction analysis, sequence tools' newline ...
                  '• Batch Processing: Automated analysis of multiple files'], ...
        'Position', [50, -100, 1000, 240], ...  % Made wider: 750 -> 1000
        'FontSize', 11, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.95, 0.95, 0.95]);
    
    % Store handles in guidata
    handles = struct('statusText', statusText, 'mainFig', mainFig);
    guidata(mainFig, handles);

    %% =======================================================================
    %% CALLBACK FUNCTIONS - CALLING MODULES
    %% =======================================================================
    
    %% Callback Functions for Bacterial Growth Analysis
    function step1Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 1: Data Preparation...');
        drawnow;
        % Call growth analysis module
        growth_analysis_module.prepareDataGUI(mainFig);
    end
    
    function step2Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 2: OD Growth Analysis...');
        drawnow;
        growth_analysis_module.analyzeODGUI(mainFig);
    end
    
    function step3Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 3: Luciferase Analysis...');
        drawnow;
        growth_analysis_module.analyzeLuciferaseGUI(mainFig);
    end

    function step4Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 4: Lum vs. OD Analysis...');
        drawnow;
        growth_analysis_module.analyzeLumVsODGUI(mainFig);
    end

    function step5Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 5: 3D Lum vs. OD vs. Time Analysis...');
        drawnow;
        growth_analysis_module.analyze3DLumVsODGUI(mainFig);
    end

    function universalPlateReaderCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Universal Plate Reader...');
        drawnow;
        
        % Running a script correctly - use the "run" command
        % We also need to make the mainFig visible in the base workspace
        assignin('base', 'mainFigureHandle', mainFig);
        run('Plate_Reader_Analysis_ver13_0');
    end
    
    %% Callback Functions for Image Analysis
    function pellicleIPCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Pellicle IP Analysis...');
        drawnow;
        image_analysis_module.runPellicleIP(handles);
    end
    
    function bacterialGIPCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting BacterialG IP Analysis...');
        drawnow;
        image_analysis_module.runBacterialGIP(handles);
    end
    
    function poreAnalysisCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Pore Analysis...');
        drawnow;
        image_analysis_module.analyze_pores_freehand_scroll();
        % Update status after completion
        set(handles.statusText, 'String', [
            'Pore Analysis completed successfully!' newline newline ...
            'Results saved in the results folder.' newline ...
            'Check the generated overlay images and analysis results.' newline newline ...
            'Ready for next operation.']);
    end

    function SangerCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Sanger analysis...');
        drawnow;
        image_analysis_module.runSangerWrapper(handles);
    end

    %% Calculator Callbacks - CALLING CALCULATORS MODULE
    function MolarityCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Molarity Calculator...');
        drawnow;
        calculators_module.MolarityCalculator(handles);
    end

    function B4Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Media Preparation Calculator...');
        drawnow;
        calculators_module.MediaPreparationCalculator(handles);
    end
    
    %% Advanced Analysis Callbacks
    function doseResponseCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Dose-Response Analysis...');
        drawnow;
        advanced_analysis_module.runDoseResponseAnalysis(handles);
    end

    function colonyCounterCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Colony Counter...');
        drawnow;
        advanced_analysis_module.runColonyCounter(handles);
    end

    function biofilmAnalysisCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Biofilm Analysis...');
        drawnow;
        advanced_analysis_module.runBiofilmAnalysis(handles);
    end

    function microscopyCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Microscopy Tools...');
        drawnow;
        advanced_analysis_module.runMicroscopyTools(handles);
    end

    function genomicsCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Genomics Tools...');
        drawnow;
        advanced_analysis_module.runGenomicsTools(handles);
    end

    function batchProcessingCallback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Batch Processing...');
        drawnow;
        advanced_analysis_module.runBatchProcessing(handles);
    end
    
end